name: Deploy infrastructure

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          cd cdk-infrastructure
          npm install

      - name: Deploy infrastructure Stack
        run: |
          cd cdk-infrastructure
          npx cdk deploy --require-approval never --outputs-file ../infrastructure-outputs.json

      - name: Upload infrastructure outputs to S3
        env:
          BUCKET_NAME: "expensetrackerinfra-arnav05"
          INFRA_FILE_NAME: "infrastructure-outputs.json"
        run: |
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME"; then
            aws s3 mb s3://$BUCKET_NAME --region ${{ env.AWS_REGION }}
          else 
            echo "Bucket "$BUCKET_NAME" already exists. Skipping bucket creation."
          fi
          echo "Uploading Bucket: $BUCKET_NAME"
          aws s3 cp ${INFRA_FILE_NAME} s3://${BUCKET_NAME}/${INFRA_FILE_NAME}
